app: sustainable-leverage-backend
service: sustainable-leverage-backend
frameworkVersion: '3'

useDotenv: true
package:
  individually: true
  excludeDevDependencies: true

custom:
  stage: ${opt:stage, 'dev'} # 'dev' is the default if no stage is provided

provider:
  name: aws
  runtime: nodejs18.x

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

functions:
  liquidator:
    handler: dist/src/liquidator/lambda-handler.handler
    name: sustainable-leverage-backend-${self:custom.stage}-liquidator
    timeout: 60
    events:
      - schedule:
          rate: rate(1 minute)
          enabled: true
    layers:
      - ${env:LAYER_ARN}
    environment:
      DB_HOST: ${env:DB_HOST}
      DB_PORT: ${env:DB_PORT}
      DB_NAME: ${env:DB_NAME}
      DB_USER: ${env:DB_USER}
      DB_PASSWORD: ${env:DB_PASSWORD}
      S3_BUCKET_CONFIG: ${env:S3_BUCKET_CONFIG}
      S3_ADDRESSES_KEY: ${env:S3_ADDRESSES_KEY}
      RPC_URL: ${env:RPC_URL}
      MAINNET_RPC_URL: ${env:MAINNET_RPC_URL}
      PRIVATE_KEY: ${env:PRIVATE_KEY}
