AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Deploys a Lambda function to monitor LvBTC pool and expire positions to balance it.

Globals:
  Function:
    Timeout: 20

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaS3SQSFullAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:*'
                  - 's3-object-lambda:*'
                Resource: '*'
              - Effect: Allow
                Action: 'sqs:*'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'logs:CreateLogStream'
                  - 'logs:CreateLogGroup'
                  - 'logs:TagResource'
                  - 'logs:PutLogEvents'
                Resource: 'arn:aws:logs:*:*:*'

  ExpiratorBotDemo:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda-handler.handler
      Runtime: nodejs16.x
      CodeUri: ./deploy-package
      FunctionName: !Sub 'ExpiratorBotDemo${FunctionNameSuffix}'
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        EveryMinuteEvent:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)
      Environment:
        Variables:
          PRIVATE_KEY: !Ref PrivateKey
          MOCK_CURVE_POOL_ADDRESS: !Ref MockCurvePoolAddress
          MAINNET_RPC_URL: !Ref MainnetRpcUrl
          RPC_URL: !Ref RpcUrl
          S3_BUCKET_CONFIG: !Ref S3BucketConfig
          S3_ADDRESSES_KEY: !Ref S3AddressesKey
          DB_HOST: !Ref DbHost
          DB_PORT: !Ref DbPort
          DB_NAME: !Ref DbName
          DB_USER: !Ref DbUser
          DB_PASSWORD: !Ref DbPassword
          NEW_RELIC_API_KEY: !Ref NewRelicAPIKey

Parameters:
  NewRelicAPIKey:
    Type: String
    Description: New Relic License Key

  PrivateKey:
    Type: String
    Description: S3 Bucket Name

  MockCurvePoolAddress:
    Type: String
    Description: Mock Curve Pool Address

  MainnetRpcUrl:
    Type: String
    Description: Mainnet RPC URL

  RpcUrl:
    Type: String
    Description: Fork RPC URL

  S3BucketConfig:
    Type: String
    Description: S3 Bucket Config

  S3AddressesKey:
    Type: String
    Description: S3 Addresses Key

  DbHost:
    Type: String
    Description: Database Host

  DbPort:
    Type: Number
    Description: Database Port

  DbName:
    Type: String
    Description: Database Name

  DbUser:
    Type: String
    Description: Database User

  DbPassword:
    Type: String
    Description: Database Password
    NoEcho: true

  FunctionNameSuffix:
    Type: String
    Description: Function Name Suffix
    Default: ''