"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CurvePoolABI__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var CurvePoolABI__factory_1 = require("./CurvePoolABI__factory");
Object.defineProperty(exports, "CurvePoolABI__factory", { enumerable: true, get: function () { return CurvePoolABI__factory_1.CurvePoolABI__factory; } });
