/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace ConvexPoolAdapter {
  export type RewardDataStruct = { token: AddressLike; amount: BigNumberish };

  export type RewardDataStructOutput = [token: string, amount: bigint] & {
    token: string;
    amount: bigint;
  };
}

export interface ConvexPoolAdapterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CONVEX_BOOSTER"
      | "CURVE_TOKEN"
      | "CVX"
      | "CVX_MAX_SUPPLY"
      | "ETH"
      | "WETH"
      | "claim"
      | "convexPid"
      | "convexRewardPool"
      | "curveLpToken"
      | "curvePool"
      | "deposit"
      | "healthFactor"
      | "indexUint"
      | "initialize"
      | "isHealthy"
      | "lpBalance"
      | "multiPoolStrategy"
      | "rewardTokens"
      | "setHealthFactor"
      | "storedUnderlyingBalance"
      | "tokensLength"
      | "totalClaimable"
      | "underlyingBalance"
      | "underlyingToken"
      | "underlyingTokenPoolIndex"
      | "useEth"
      | "withdraw"
      | "zapper"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;

  encodeFunctionData(
    functionFragment: "CONVEX_BOOSTER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CURVE_TOKEN",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "CVX", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "CVX_MAX_SUPPLY",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "ETH", values?: undefined): string;
  encodeFunctionData(functionFragment: "WETH", values?: undefined): string;
  encodeFunctionData(functionFragment: "claim", values?: undefined): string;
  encodeFunctionData(functionFragment: "convexPid", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "convexRewardPool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "curveLpToken",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "curvePool", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "healthFactor",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "indexUint", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      AddressLike,
      boolean,
      boolean,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(functionFragment: "isHealthy", values?: undefined): string;
  encodeFunctionData(functionFragment: "lpBalance", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "multiPoolStrategy",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rewardTokens",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setHealthFactor",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "storedUnderlyingBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tokensLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalClaimable",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "underlyingBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "underlyingToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "underlyingTokenPoolIndex",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "useEth", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "zapper", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "CONVEX_BOOSTER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CURVE_TOKEN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "CVX", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "CVX_MAX_SUPPLY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ETH", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "WETH", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "convexPid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "convexRewardPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "curveLpToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "curvePool", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "healthFactor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "indexUint", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isHealthy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lpBalance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "multiPoolStrategy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rewardTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setHealthFactor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "storedUnderlyingBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokensLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalClaimable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "underlyingBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "underlyingToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "underlyingTokenPoolIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "useEth", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "zapper", data: BytesLike): Result;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ConvexPoolAdapter extends BaseContract {
  connect(runner?: ContractRunner | null): ConvexPoolAdapter;
  waitForDeployment(): Promise<this>;

  interface: ConvexPoolAdapterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CONVEX_BOOSTER: TypedContractMethod<[], [string], "view">;

  CURVE_TOKEN: TypedContractMethod<[], [string], "view">;

  CVX: TypedContractMethod<[], [string], "view">;

  CVX_MAX_SUPPLY: TypedContractMethod<[], [bigint], "view">;

  ETH: TypedContractMethod<[], [string], "view">;

  WETH: TypedContractMethod<[], [string], "view">;

  claim: TypedContractMethod<[], [void], "nonpayable">;

  convexPid: TypedContractMethod<[], [bigint], "view">;

  convexRewardPool: TypedContractMethod<[], [string], "view">;

  curveLpToken: TypedContractMethod<[], [string], "view">;

  curvePool: TypedContractMethod<[], [string], "view">;

  deposit: TypedContractMethod<
    [_amount: BigNumberish, _minCurveLpAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  healthFactor: TypedContractMethod<[], [bigint], "view">;

  indexUint: TypedContractMethod<[], [boolean], "view">;

  initialize: TypedContractMethod<
    [
      _curvePool: AddressLike,
      _multiPoolStrategy: AddressLike,
      _convexPid: BigNumberish,
      _tokensLength: BigNumberish,
      _zapper: AddressLike,
      _useEth: boolean,
      _indexUint: boolean,
      _underlyingTokenPoolIndex: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  isHealthy: TypedContractMethod<[], [boolean], "view">;

  lpBalance: TypedContractMethod<[], [bigint], "view">;

  multiPoolStrategy: TypedContractMethod<[], [string], "view">;

  rewardTokens: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  setHealthFactor: TypedContractMethod<
    [_newHealthFactor: BigNumberish],
    [void],
    "nonpayable"
  >;

  storedUnderlyingBalance: TypedContractMethod<[], [bigint], "view">;

  tokensLength: TypedContractMethod<[], [bigint], "view">;

  totalClaimable: TypedContractMethod<
    [],
    [ConvexPoolAdapter.RewardDataStructOutput[]],
    "view"
  >;

  underlyingBalance: TypedContractMethod<[], [bigint], "view">;

  underlyingToken: TypedContractMethod<[], [string], "view">;

  underlyingTokenPoolIndex: TypedContractMethod<[], [bigint], "view">;

  useEth: TypedContractMethod<[], [boolean], "view">;

  withdraw: TypedContractMethod<
    [_amount: BigNumberish, _minReceiveAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  zapper: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CONVEX_BOOSTER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "CURVE_TOKEN"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "CVX"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "CVX_MAX_SUPPLY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ETH"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "WETH"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "claim"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "convexPid"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "convexRewardPool"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "curveLpToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "curvePool"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [_amount: BigNumberish, _minCurveLpAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "healthFactor"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "indexUint"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      _curvePool: AddressLike,
      _multiPoolStrategy: AddressLike,
      _convexPid: BigNumberish,
      _tokensLength: BigNumberish,
      _zapper: AddressLike,
      _useEth: boolean,
      _indexUint: boolean,
      _underlyingTokenPoolIndex: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isHealthy"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "lpBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "multiPoolStrategy"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "rewardTokens"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "setHealthFactor"
  ): TypedContractMethod<
    [_newHealthFactor: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "storedUnderlyingBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "tokensLength"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalClaimable"
  ): TypedContractMethod<
    [],
    [ConvexPoolAdapter.RewardDataStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "underlyingBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "underlyingToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "underlyingTokenPoolIndex"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "useEth"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [_amount: BigNumberish, _minReceiveAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "zapper"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;

  filters: {
    "Initialized(uint8)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
  };
}
