name: Acceptance Stage

on:
  pull_request:
    branches:
      - main 

env:
  AWS_REGION: us-east-1
  EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }} 
  EC2_HOST: ${{ secrets.EC2_HOST }} 
  DEMO_EC2_HOST: ${{ secrets.DEMO_EC2_HOST }} 
  EC2_USER: ubuntu
  PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
  API_DEVOPS_EVENT_CATCHER: ${{ vars.API_DEVOPS_EVENT_CATCHER }}
  DEVOPS_EVENTS_SECRET_TOKEN: ${{ secrets.DEVOPS_EVENTS_SECRET_TOKEN }}

jobs:
  acceptance-test:
    runs-on: ubuntu-latest
    steps:
      - name: Acceptance Test
        run: | 
            echo "placeholder for acceptance test"
      