name: Acceptance Stage

on:
  pull_request:
    branches:
      - main 
  workflow_dispatch:

env:
  ENVIRONMENT: ${{ vars.DEFAULT_ENVIRONMENT }}

  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
  API_DEVOPS_EVENT_CATCHER: ${{ vars.API_DEVOPS_EVENT_CATCHER }}
  DEVOPS_EVENTS_SECRET_TOKEN: ${{ secrets.DEVOPS_EVENTS_SECRET_TOKEN }}

jobs:
  acceptance-test:
    runs-on: ubuntu-latest
    steps:
      - name: Acceptance Test
        run: | 
            echo "placeholder for acceptance test"
      
