name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }} 
  EC2_HOST: ${{ secrets.EC2_HOST }} 
  DEMO_EC2_HOST: ${{ secrets.DEMO_EC2_HOST }} 
  EC2_USER: ubuntu
  PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
  API_DEVOPS_EVENT_CATCHER: ${{ vars.API_DEVOPS_EVENT_CATCHER }}
  DEVOPS_EVENTS_SECRET_TOKEN: ${{ secrets.DEVOPS_EVENTS_SECRET_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      trigger-deploy: ${{ steps.set_output.outputs.trigger-deploy }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
  
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
      - name: Install dependencies
        run: yarn
      - name: Test
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          S3_BUCKET_CONFIG: ${{ secrets.S3_BUCKET_CONFIG }}
          S3_ADDRESSES_KEY: ${{ secrets.S3_ADDRESSES_KEY }}
          RPC_URL: ${{ secrets.RPC_URL }}
          MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
          NEW_RELIC_API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          echo "TEST_START=$(date +%s)" >> $GITHUB_ENV  
          yarn test

      - name: Test-Demo
        env:
          DB_HOST: ${{ secrets.DEMO_DB_HOST }}
          DB_PORT: ${{ secrets.DEMO_DB_PORT }}
          DB_NAME: ${{ secrets.DEMO_DB_NAME }}
          DB_USER: ${{ secrets.DEMO_DB_USER }}
          DB_PASSWORD: ${{ secrets.DEMO_DB_PASSWORD }}
          S3_BUCKET_CONFIG: ${{ secrets.S3_BUCKET_CONFIG }}
          S3_ADDRESSES_KEY: ${{ secrets.DEMO_S3_ADDRESSES_KEY }}
          RPC_URL: ${{ secrets.DEMO_RPC_URL }}
          MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
          NEW_RELIC_API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          yarn test

          end=$(date +%s)
          duration=$((end-${{ env.TEST_START }}))

          echo "DURATION=$duration" >> $GITHUB_ENV
          echo "Time taken to run the tests: $duration seconds"

      - name: Report test run time
        run: |
          echo "Time taken to run the tests: ${{ env.DURATION }} seconds"
          yarn add install axios dotenv
          node devops/metrics/src/cicd_script/report_devops_event.js ${{ github.repository }} "test_pass" '{"duration": ${{ env.DURATION }}}'

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
          
      - name: Set output for deploy
        id: set_output
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: echo "::set-output name=trigger-deploy::true"
    

  create-deploy-trigger:
    runs-on: ubuntu-latest
    needs: [test] 
    if: success()            
    steps:
      - name: Create Trigger File
        run: echo "Tests passed" > deploy_trigger.txt
      - name: Upload Trigger Artifact
        uses: actions/upload-artifact@v4
        with:
          name: deploy-trigger
          path: deploy_trigger.txt
