name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }} 
  EC2_HOST: ${{ secrets.EC2_HOST }} 
  DEMO_EC2_HOST: ${{ secrets.DEMO_EC2_HOST }} 
  EC2_USER: ubuntu
  PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
      - name: Install dependencies
        run: yarn
      - name: Test
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          S3_BUCKET_CONFIG: ${{ secrets.S3_BUCKET_CONFIG }}
          S3_ADDRESSES_KEY: ${{ secrets.S3_ADDRESSES_KEY }}
          RPC_URL: ${{ secrets.RPC_URL }}
          MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
          NEW_RELIC_API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          start=$(date +%s)
          
          yarn test

          end=$(date +%s)
          duration=$((end-start))
          echo "DURATION=$duration" >> $GITHUB_ENV
          echo "Time taken to run the tests: $duration seconds"

      - name: Report test run time
        run: |
          echo "Time taken to run the tests: ${{ env.DURATION }} seconds"
          yarn add install axios dotenv
          pwd
          ls devops/metrics/src/cicd_script
          node devops/metrics/src/cicd_script/report_devops_event.js ${{ github.repository }} "test_pass" '{"duration": ${{ env.DURATION }}}'
